.Dd June 16, 2014
.Dt SDL-JSTEST 1
.Os
.Sh NAME
.Nm sdl-jstest
.Nd joystick test application for SDL
.Sh SYNOPSIS
.Nm sdl-jstest
.Op Fl Fl help
.Op Fl Fl version
.Op Fl Fl list
.Op Fl Fl test Ar JOYNUM
.Op Fl Fl event Ar JOYNUM
.Sh DESCRIPTION
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display help text and exit.
.It Fl Fl version
Display the version number and exit.
.It Fl Fl list
Search for available joysticks and list their properties.
.It Fl Fl test Ar JOYNUM
Display a graphical representation of the current joystick state.
.It Fl Fl event Ar JOYNUM
Display the events that are received from the joystick.
.El
.Sh ENVIRONMENT
What SDL detects as axis, what is treated as a hat and what is
handled as normal axis can be configured with the environment
variable
.Ev SDL_LINUX_JOYSTICK :
.Bl -tag -width Ds
.It Ev SDL_LINUX_JOYSTICK
Special joystick configuration string for Unix.
The format is
.Qq Ar name numaxes numhats numballs
where
.Ar name
is the name string of the joystick (possibly in single quotes),
and the rest are the number of axes, hats and balls respectively.
.El
.Pp
A complete list of which environment variables SDL supports can be found at:
.Lk http://sdl.beuc.net/sdl.wiki/SDL_envvars
.Sh EXAMPLES
A simple example would be:
.D1 $ export SDL_LINUX_JOYSTICK="\(aqXbox Gamepad (userspace driver)\(aq 6 0 0"
.Pp
Which makes all axes be handled as normal axis and none as hat,
as most games don't use hats.
.Sh SEE ALSO
.Xr jstest 1 ,
.Xr jstest-gtk 1 ,
.Xr sdl2-jstest 1 ,
.Xr xboxdrv 1
